### ISSUE TITLE
I've been giving a look to your new Gulp plugin, here's some questions.

### ISSUE THREAD

**Issue by becarlos** [jblandino/gulp-all-tasks#4]
Hi Joel, I've been giving a look to your new Gulp plugin, here's some questions:

Could you help me with something I can't get it into your code.

Why you use double semicolons ";;", at the end of that statement on line 18 in "index.js":

' ' '
return text.replace(regex, replace);;
' ' '

I had another when I was reading your readme.md file:

"You can install any plugin and this module you can convert the name to a function within gulp, For example, if you install grunt-uglify you can use it inside grunt as grunt_uglify()",

This made me to wonder whether can I use Grunt plugins within my Gulp workflow only using "gulp-all-tasks" or you just wrote a tiny issue on your readme file.

Thanks, I hope I've helped a bit.

PS: Have you been using JSHint? I could continue describing some question about "Function name" regarding Camel Case, in both using a Gulp plugin after have added into the gulpfile, and when you replace - for _ .

**Comment by alblandino** [comment]
Hey, Hi @becarlos 

The two semicolons apparently was a mistake that I had at the time of the commit, but the strange thing was that the 'use strict' I allowed to do that but let me review it.
Line [#18](https://github.com/jblandino/gulp-all-tasks/blob/master/index.js#L18)

If you use JSHint but function_name() I found it cleaner than functionName() since it is more likely to have some method in the global scope.

Hey, if you want you can make a fork and add what you think.

Merged #5 
Thanks!
